defaults:
  - /schema/model: aegrldo
  - defaults
first_conv: false
maxpool1: false
latent_dim: 32
lr: 0.0001
weight_decay: 1e-08
lr_initial_restart: 10
lr_restart_mult: 2
lr_sched_interval: epoch
lr_sched_freq: 1